(function() {
    const eliminationData = {
        "Penicillin G": { hu: "Renális", en: "Renal", de: "Renal" },
        "Penicillin V": { hu: "Renális", en: "Renal", de: "Renal" },
        "Oxacillin": { hu: "Hepatikus/Renális", en: "Hepatic/Renal", de: "Hepatisch/Renal" },
        "Amoxicillin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Amoxicillin-clavulanate": { hu: "Renális", en: "Renal", de: "Renal" },
        "Ampicillin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Ampicillin-sulbactam": { hu: "Renális", en: "Renal", de: "Renal" },
        "Flucloxacillin": { hu: "Renális/Hepatikus", en: "Renal/Hepatic", de: "Renal/Hepatisch" },
        "Piperacillin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Piperacillin-tazobactam": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefazolin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefoxitin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefalexin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefaclor": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefuroxime": { hu: "Renális", en: "Renal", de: "Renal" },
        "Ceftriaxone": { hu: "Renális/Biliaris", en: "Renal/Biliary", de: "Renal/Biliär" },
        "Cefotaxime": { hu: "Renális", en: "Renal", de: "Renal" },
        "Ceftazidime": { hu: "Renális", en: "Renal", de: "Renal" },
        "Ceftazidime-avibactam": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefepime": { hu: "Renális", en: "Renal", de: "Renal" },
        "Ceftolozane-tazobactam": { hu: "Renális", en: "Renal", de: "Renal" },
        "Ceftaroline-avibactam": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefepime-taniborbactam": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefiderocol": { hu: "Renális", en: "Renal", de: "Renal" },
        "Meropenem": { hu: "Renális", en: "Renal", de: "Renal" },
        "Imipenem-cilastatin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Ertapenem": { hu: "Renális", en: "Renal", de: "Renal" },
        "Doripenem": { hu: "Renális", en: "Renal", de: "Renal" },
        "Imipenem-cilastatin-relebactam": { hu: "Renális", en: "Renal", de: "Renal" },
        "Meropenem-vaborbactam": { hu: "Renális", en: "Renal", de: "Renal" },
        "Aztreonam": { hu: "Renális", en: "Renal", de: "Renal" },
        "Gentamicin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Amikacin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Plazomicin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Nalidixic acid": { hu: "Renális (májban metabolizálódik)", en: "Renal (hepatic metabolism)", de: "Renal (hepatischer Metabolismus)" },
        "Ofloxacin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Ciprofloxacin": { hu: "Renális/Hepatikus", en: "Renal/Hepatic", de: "Renal/Hepatisch" },
        "Levofloxacin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Delafloxacin": { hu: "Renális/Hepatikus", en: "Renal/Hepatic", de: "Renal/Hepatisch" },
        "Moxifloxacin": { hu: "Hepatikus/Biliaris", en: "Hepatic/Biliary", de: "Hepatisch/Biliär" },
        "Vancomycin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Teicoplanin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Telavancin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Dalbavancin": { hu: "Renális/Hepatikus", en: "Renal/Hepatic", de: "Renal/Hepatisch" },
        "Oritavancin": { hu: "Hepatikus (lassú)", en: "Hepatic (slow)", de: "Hepatisch (langsam)" },
        "Erythromycin": { hu: "Biliaris/Hepatikus", en: "Biliary/Hepatic", de: "Biliär/Hepatisch" },
        "Azithromycin": { hu: "Biliaris", en: "Biliary", de: "Biliär" },
        "Clarithromycin": { hu: "Renális/Hepatikus", en: "Renal/Hepatic", de: "Renal/Hepatisch" },
        "Roxithromycin": { hu: "Hepatikus/Biliaris", en: "Hepatic/Biliary", de: "Hepatisch/Biliär" },
        "Spiramycin": { hu: "Biliaris", en: "Biliary", de: "Biliär" },
        "Clindamycin": { hu: "Hepatikus/Biliaris", en: "Hepatic/Biliary", de: "Hepatisch/Biliär" },
        "Doxycycline": { hu: "Hepatikus/Biliaris/Renális", en: "Hepatic/Biliary/Renal", de: "Hepatisch/Biliär/Renal" },
        "Tigecycline": { hu: "Biliaris/Fekális", en: "Biliary/Fecal", de: "Biliär/Fäkal" },
        "Minocycline": { hu: "Hepatikus", en: "Hepatic", de: "Hepatisch" },
        "Eravacycline": { hu: "Fekális/Renális", en: "Fecal/Renal", de: "Fäkal/Renal" },
        "Sarecycline": { hu: "Fekális", en: "Fecal", de: "Fäkal" },
        "Omadacycline": { hu: "Fekális/Renális", en: "Fecal/Renal", de: "Fäkal/Renal" },
        "Linezolid": { hu: "Renális/Nem-renális", en: "Renal/Non-renal", de: "Renal/Nicht-renal" },
        "Tedizolid": { hu: "Fekális/Hepatikus", en: "Fecal/Hepatic", de: "Fäkal/Hepatisch" },
        "Daptomycin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Metronidazole": { hu: "Hepatikus/Renális", en: "Hepatic/Renal", de: "Hepatisch/Renal" },
        "Quinupristin-dalfopristin": { hu: "Hepatikus/Biliaris", en: "Hepatic/Biliary", de: "Hepatisch/Biliär" },
        "Chloramphenicol": { hu: "Hepatikus (metabolizmus)", en: "Hepatic (metabolism)", de: "Hepatisch (Metabolismus)" },
        "Fosfomycin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Fidaxomicin": { hu: "Fekális", en: "Fecal", de: "Fäkal" },
        "Mupirocin": { hu: "Renális (metabolit)", en: "Renal (metabolite)", de: "Renal (Metabolit)" },
        "Fusidic acid": { hu: "Biliaris", en: "Biliary", de: "Biliär" },
        "TMP-SMX": { hu: "Renális", en: "Renal", de: "Renal" },
        "Nitrofurantoin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Rifampin": { hu: "Hepatikus/Biliaris", en: "Hepatic/Biliary", de: "Hepatisch/Biliär" },
        "Rifabutin": { hu: "Renális/Biliaris", en: "Renal/Biliary", de: "Renal/Biliär" },
        "Rifaximin": { hu: "Fekális", en: "Fecal", de: "Fäkal" },
        "Polymyxin B": { hu: "Nem-renális", en: "Non-renal", de: "Nicht-renal" },
        "Bacitracin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Colistin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Fluconazole": { hu: "Renális", en: "Renal", de: "Renal" },
        "Voriconazole": { hu: "Hepatikus", en: "Hepatic", de: "Hepatisch" },
        "Caspofungin": { hu: "Hepatikus", en: "Hepatic", de: "Hepatisch" },
        "Amphotericin B": { hu: "Renális/Biliaris", en: "Renal/Biliary", de: "Renal/Biliär" },
        "Vancomycin (inhalation)": { hu: "Renális", en: "Renal", de: "Renal" },
        "Tobramycin (inhalation)": { hu: "Renális", en: "Renal", de: "Renal" },
        "Lefamulin": { hu: "Fekális/Renális", en: "Fecal/Renal", de: "Fäkal/Renal" },
        "Nafcillin": { hu: "Hepatikus", en: "Hepatic", de: "Hepatisch" },
        "Dicloxacillin": { hu: "Renális/Hepatikus", en: "Renal/Hepatic", de: "Renal/Hepatisch" },
        "Cefotetan": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefoperazone": { hu: "Biliaris", en: "Biliary", de: "Biliär" },
        "Ceftizoxime": { hu: "Renális", en: "Renal", de: "Renal" },
        "Ceftaroline": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefepime-enmetazobactam": { hu: "Renális", en: "Renal", de: "Renal" },
        "Ceftobiprole": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefadroxil": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefixime": { hu: "Renális/Biliaris", en: "Renal/Biliary", de: "Renal/Biliär" },
        "Cefprozil": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefdinir": { hu: "Renális", en: "Renal", de: "Renal" },
        "Ceftibuten": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefpodoxime": { hu: "Renális", en: "Renal", de: "Renal" },
        "Tobramycin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Cefditoren": { hu: "Renális", en: "Renal", de: "Renal" },
        "Telithromycin": { hu: "Hepatikus", en: "Hepatic", de: "Hepatisch" },
        "Tetracycline": { hu: "Renális/Biliaris", en: "Renal/Biliary", de: "Renal/Biliär" },
        "Pristinamycin": { hu: "Biliaris", en: "Biliary", de: "Biliär" },
        "Pivmecillinam": { hu: "Renális", en: "Renal", de: "Renal" },
        "Norfloxacin": { hu: "Renális/Hepatikus", en: "Renal/Hepatic", de: "Renal/Hepatisch" },
        "Prulifloxacin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Gemifloxacin": { hu: "Renális/Fekális", en: "Renal/Fecal", de: "Renal/Fäkal" },
        "Gatifloxacin": { hu: "Renális", en: "Renal", de: "Renal" },
        "Aztreonam-Avibactam": { hu: "Renális", en: "Renal", de: "Renal" }
    };

    const updateAntibiotics = (antibiotics) => {
        if (!antibiotics) return;
        antibiotics.forEach(ab => {
            const name = ab.name.en;
            if (eliminationData[name]) {
                ab.elimination = eliminationData[name];
            }
        });
    };

    if (window.antibiotics_hu) updateAntibiotics(window.antibiotics_hu);
    if (window.antibiotics_en) updateAntibiotics(window.antibiotics_en);
    if (window.antibiotics_de) updateAntibiotics(window.antibiotics_de);
})();